// AUTO-GENERATED BY scripts/sync_nfl_data.py
// Preseason 2024 NFL Roster Realignment: Stars, Journeymen & Rookies
// Synced: 2026-09-24 15:55:46

import { Client, GMProfile } from '../types/game';

export const REAL_NFL_CLIENTS: Client[] = [
  {
    "id": "ceedee-lamb",
    "name": "CeeDee Lamb",
    "position": "WR",
    "positionFull": "All-Pro Wide Receiver / Target Engine",
    "age": 25,
    "team": "Dallas Cowboys",
    "teamLogoAbbr": "DAL",
    "rating": 97,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/tfuj9njqdw2dovkwhryc",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
    "teamColor": "#002244",
    "college": "Oklahoma",
    "dataSource": "spotrac",
    "tier": "STAR",
    "situationalTag": "TRAINING CAMP HOLDOUT ($50K/DAY FINES)",
    "contractType": "MEGA_EXTENSION",
    "healthDurability": 95,
    "schemeFitScore": 99,
    "schemeType": "Spread Option",
    "publicLeverageScore": 96,
    "patienceAndTrust": 68,
    "currentStatus": "Pending Extension",
    "currentSalary": 17.9,
    "warRoom": {
      "thesisStatement": "CeeDee Lamb accounted for 30.5% of Dallas' target share in 2023 with 135 receptions. Jerry Jones' public claim of 'no urgency' is pure posturing\u2014Dak Prescott's entire passing structure evaporates without Lamb on the perimeter.",
      "leverageTimeline": [
        "CAMP DAY 1: Lamb initiates full holdout; daily mandatory $50,000 un-waivable fines begin accumulating.",
        "AUGUST 8: Jerry Jones shocks media: 'I don't have a sense of urgency about getting to a deal with CeeDee.' Lamb retweets 'lol' from South Florida training facility.",
        "PRESEASON W2: Joint practices with the Rams expose complete lack of separation among backup receivers Brandin Cooks and Jalen Tolbert."
      ],
      "replacementCost": {
        "draftCapitalCost": "Dallas has zero internal succession plan; without Lamb, opposing defenses double Jake Ferguson and blitz with impunity.",
        "rookieVarianceDelta": "Dak Prescott's passer rating drops from 105.9 with Lamb to 78.4 when targeted to all other wideouts.",
        "capOpportunityCost": "Justin Jefferson reset the market at $35.0M AAV; every week Dallas delays adds $500k to Lamb's guarantee demands.",
        "qbPressureDelta": "Led NFL with 135 receptions and 1,749 yards in 2023; 1st in first-down conversions.",
        "pickWasted": "Round 1, Pick 17"
      },
      "targetAsk": {
        "term": 4,
        "totalValue": 136,
        "aav": 34.0,
        "practicalGuarantees": 100,
        "firstYearCashFlowPct": 42
      },
      "comparables": [
        {
          "player": "Justin Jefferson",
          "team": "MIN",
          "aav": 35.0,
          "guarantees": 110.0,
          "year": 2024
        },
        {
          "player": "A.J. Brown",
          "team": "PHI",
          "aav": 32.0,
          "guarantees": 84.0,
          "year": 2024
        },
        {
          "player": "Amon-Ra St. Brown",
          "team": "DET",
          "aav": 30.0,
          "guarantees": 77.0,
          "year": 2024
        }
      ],
      "keyStats": [
        {
          "label": "Receptions (2023)",
          "value": "135",
          "rank": "1st in NFL"
        },
        {
          "label": "Receiving Yards",
          "value": "1,749",
          "rank": "2nd in NFL"
        },
        {
          "label": "Target Share",
          "value": "30.5%",
          "rank": "Top Tier Alpha"
        }
      ]
    }
  },
  {
    "id": "trent-williams",
    "name": "Trent Williams",
    "position": "OT",
    "positionFull": "Hall of Fame Left Tackle / Blindside Anchor",
    "age": 36,
    "team": "San Francisco 49ers",
    "teamLogoAbbr": "SF",
    "rating": 98,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/pngn7zttto574ellwslr",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
    "teamColor": "#AA0000",
    "college": "Oklahoma",
    "dataSource": "spotrac",
    "tier": "STAR",
    "situationalTag": "VETERAN HOLDOUT ($0 GUARANTEED REMAINING)",
    "contractType": "MEGA_EXTENSION",
    "healthDurability": 88,
    "schemeFitScore": 99,
    "schemeType": "Wide Zone",
    "publicLeverageScore": 98,
    "patienceAndTrust": 75,
    "currentStatus": "Pending Extension",
    "currentSalary": 20.05,
    "warRoom": {
      "thesisStatement": "Trent Williams is the single most irreplaceable non-QB in the NFL. He has 3 years left on his contract with ZERO guaranteed cash. At 36, he is staging a principled holdout because Kyle Shanahan's outside-zone playbook completely collapses without him.",
      "leverageTimeline": [
        "CAMP REPORT: Williams fails to report to Santa Clara, racking up mandatory fines in Texas.",
        "JOINT PRACTICES: 49ers backup offensive line surrenders 7 sacks in single afternoon against Saints pass rush.",
        "BROCK PURDY PANIC: 49ers front office recognizes that Purdy's blindside pressure rate jumps 300% without Williams anchoring."
      ],
      "replacementCost": {
        "draftCapitalCost": "49ers have Pick 31; cannot draft a competent left tackle. Jaylon Moore is a severe drop-off.",
        "rookieVarianceDelta": "Christian McCaffrey averages 5.8 yards per carry behind Trent vs 3.4 yards to any other gap.",
        "capOpportunityCost": "Refusing to adjust Trent's contract risks an opening month without your primary offensive cog in a Super Bowl window.",
        "qbPressureDelta": "Allowed zero sacks in 2023; 11-time consecutive Pro Bowler.",
        "pickWasted": "Round 1, Pick 4"
      },
      "targetAsk": {
        "term": 3,
        "totalValue": 82.5,
        "aav": 27.5,
        "practicalGuarantees": 48,
        "firstYearCashFlowPct": 46
      },
      "comparables": [
        {
          "player": "Penei Sewell",
          "team": "DET",
          "aav": 28.0,
          "guarantees": 85.0,
          "year": 2024
        },
        {
          "player": "Laremy Tunsil",
          "team": "HOU",
          "aav": 25.0,
          "guarantees": 60.0,
          "year": 2023
        }
      ],
      "keyStats": [
        {
          "label": "PFF Run Blocking Grade",
          "value": "92.5",
          "rank": "1st in NFL"
        },
        {
          "label": "Sacks Allowed",
          "value": "0",
          "rank": "Flawless"
        },
        {
          "label": "Pro Bowl Selections",
          "value": "11x",
          "rank": "Active Leader"
        }
      ]
    }
  },
  {
    "id": "haason-reddick",
    "name": "Haason Reddick",
    "position": "EDGE",
    "positionFull": "Disruptive Speed Rusher / Edge Specialist",
    "age": 29,
    "team": "New York Jets",
    "teamLogoAbbr": "NYJ",
    "rating": 91,
    "headshotUrl": "https://static.www.nfl.com/image/private/f_auto,q_auto/league/qqfxdnlmmyzbh27lmxgi",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
    "teamColor": "#003F2D",
    "college": "Temple",
    "dataSource": "spotrac",
    "tier": "STAR",
    "situationalTag": "PRESEASON TRADE HOLDOUT (REFUSING TO REPORT)",
    "contractType": "MEGA_EXTENSION",
    "healthDurability": 91,
    "schemeFitScore": 94,
    "schemeType": "Man Coverage",
    "publicLeverageScore": 88,
    "patienceAndTrust": 60,
    "currentStatus": "Impasse",
    "currentSalary": 14.25,
    "warRoom": {
      "thesisStatement": "Traded from Philadelphia to New York in March, Reddick was promised a contract resolution. With zero guaranteed money in the final year of his deal, he is refusing to report to Florham Park, incurring over $2M in fines.",
      "leverageTimeline": [
        "MARCH TRADE: Jets send conditional 2026 pick to Eagles for Reddick; contract extension talks stall.",
        "JULY 23: Reddick fails to report to training camp; placed on Reserve/Did Not Report list.",
        "AUGUST 12: Reddick formally requests a trade from the Jets; GM Joe Douglas publicly refuses."
      ],
      "replacementCost": {
        "draftCapitalCost": "Jets already surrendered draft capital and lost Bryce Huff in free agency; edge depth is razor-thin.",
        "rookieVarianceDelta": "Without Reddick, Jets pass rush win rate drops from top-5 to 18th in simulation models.",
        "capOpportunityCost": "Jets have $18M in cap room; holding out star rusher while Aaron Rodgers is 40 years old wastes their championship window.",
        "qbPressureDelta": "4 consecutive seasons with 11+ sacks (50.5 total sacks over last 4 years).",
        "pickWasted": "Round 1, Pick 13"
      },
      "targetAsk": {
        "term": 3,
        "totalValue": 66,
        "aav": 22.0,
        "practicalGuarantees": 46,
        "firstYearCashFlowPct": 45
      },
      "comparables": [
        {
          "player": "Danielle Hunter",
          "team": "HOU",
          "aav": 24.5,
          "guarantees": 48.0,
          "year": 2024
        },
        {
          "player": "Montez Sweat",
          "team": "CHI",
          "aav": 24.5,
          "guarantees": 62.0,
          "year": 2023
        },
        {
          "player": "Josh Sweat",
          "team": "PHI",
          "aav": 18.0,
          "guarantees": 20.0,
          "year": 2024
        }
      ],
      "keyStats": [
        {
          "label": "Sacks (Last 4 Yrs)",
          "value": "50.5",
          "rank": "3rd in NFL"
        },
        {
          "label": "Forced Fumbles",
          "value": "13",
          "rank": "1st in NFL"
        },
        {
          "label": "Pass Rush Win Rate",
          "value": "19.8%",
          "rank": "Elite"
        }
      ]
    }
  },
  {
    "id": "justin-simmons",
    "name": "Justin Simmons",
    "position": "S",
    "positionFull": "Two-Time All-Pro Free Safety / Secondary Leader",
    "age": 30,
    "team": "Atlanta Falcons",
    "teamLogoAbbr": "ATL",
    "rating": 90,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/hepfele9gi8zbjin8kbf",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
    "teamColor": "#A71930",
    "college": "Boston College",
    "dataSource": "spotrac",
    "tier": "JOURNEYMAN",
    "situationalTag": "CAP CASUALTY PROVE-IT DEAL (LATE AUGUST SIGNING)",
    "contractType": "PROVE_IT",
    "healthDurability": 90,
    "schemeFitScore": 97,
    "schemeType": "Split-Safety",
    "publicLeverageScore": 84,
    "patienceAndTrust": 80,
    "currentStatus": "Pending Extension",
    "currentSalary": 7.5,
    "warRoom": {
      "thesisStatement": "Released by Denver in March as a $14.5M cap casualty despite earning 2nd-Team All-Pro honors. He patient waited out the market until training camp injuries created an urgent vacancy in Atlanta's secondary.",
      "leverageTimeline": [
        "MARCH: Released by Broncos; refuses lowball early free agency safety offers.",
        "AUGUST 12: Visits New Orleans and Atlanta; Falcons aggressively move to seal the deal to pair with Jessie Bates III.",
        "CONTRACT GOAL: Secure a 1-year prove-it structure with $5M+ guaranteed and achievable interception escalators."
      ],
      "replacementCost": {
        "draftCapitalCost": "Falcons spent draft capital on Michael Penix Jr; secondary needed instant veteran communication.",
        "rookieVarianceDelta": "Pairing Simmons with Jessie Bates III gives Atlanta the #1 safety tandem in EPA allowed.",
        "capOpportunityCost": "Signing Simmons at $7.5M is a discount compared to multi-year safety commitments.",
        "qbPressureDelta": "30 career interceptions (leads all NFL defenders since 2016).",
        "pickWasted": "Round 3, Pick 98"
      },
      "targetAsk": {
        "term": 1,
        "totalValue": 8.0,
        "aav": 8.0,
        "practicalGuarantees": 6.0,
        "firstYearCashFlowPct": 60
      },
      "comparables": [
        {
          "player": "Jordan Poyer",
          "team": "MIA",
          "aav": 2.0,
          "guarantees": 1.0,
          "year": 2024
        },
        {
          "player": "Geno Stone",
          "team": "CIN",
          "aav": 7.0,
          "guarantees": 6.0,
          "year": 2024
        }
      ],
      "keyStats": [
        {
          "label": "Career Interceptions",
          "value": "30",
          "rank": "1st in NFL"
        },
        {
          "label": "All-Pro Honors",
          "value": "4x",
          "rank": "Elite Pedigree"
        },
        {
          "label": "Passer Rating in Coverage",
          "value": "59.4",
          "rank": "Top 5 Safety"
        }
      ]
    }
  },
  {
    "id": "stephon-gilmore",
    "name": "Stephon Gilmore",
    "position": "EDGE",
    "positionFull": "Former Defensive Player of the Year / Boundary CB",
    "age": 33,
    "team": "Minnesota Vikings",
    "teamLogoAbbr": "MIN",
    "rating": 88,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/rzqv9harev8c0excxzfz",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
    "teamColor": "#4F2683",
    "college": "South Carolina",
    "dataSource": "spotrac",
    "tier": "JOURNEYMAN",
    "situationalTag": "EMERGENCY CAMP SIGNING (SECONDARY INJURY REPLACEMENT)",
    "contractType": "PROVE_IT",
    "healthDurability": 86,
    "schemeFitScore": 96,
    "schemeType": "Man Coverage",
    "publicLeverageScore": 86,
    "patienceAndTrust": 82,
    "currentStatus": "Pending Extension",
    "currentSalary": 10.0,
    "warRoom": {
      "thesisStatement": "Minnesota suffered devastating training camp injuries in their secondary (Mekhi Blackmon torn ACL, Shaquill Griffin hamstring). Brian Flores' blitz-heavy scheme requires an experienced boundary corner who can hold up on an island.",
      "leverageTimeline": [
        "AUGUST 2: Vikings lose starting CB Blackmon to season-ending ACL injury in first scrimmage.",
        "AUGUST 11: Kwesi Adofo-Mensah flies Gilmore in for emergency physical and meeting with Brian Flores.",
        "AUGUST 18: Gilmore agrees to terms on a 1-year contract worth up to $10M ($7M fully guaranteed)."
      ],
      "replacementCost": {
        "draftCapitalCost": "Zero draft options in August; waiver wire corners lack press-man capability.",
        "rookieVarianceDelta": "Flores blitzes on 51% of snaps; playing backup corners in Cover 0 results in explosive touchdowns.",
        "capOpportunityCost": "Minnesota has surplus cap space; paying for Gilmore prevents defensive collapse.",
        "qbPressureDelta": "Allowed just 54.4% completion rate on 580 coverage snaps in Dallas in 2023.",
        "pickWasted": "Round 1, Pick 10"
      },
      "targetAsk": {
        "term": 1,
        "totalValue": 10.0,
        "aav": 10.0,
        "practicalGuarantees": 7.0,
        "firstYearCashFlowPct": 70
      },
      "comparables": [
        {
          "player": "Patrick Peterson",
          "team": "PIT",
          "aav": 7.0,
          "guarantees": 5.8,
          "year": 2023
        },
        {
          "player": "Adoree' Jackson",
          "team": "NYG",
          "aav": 6.0,
          "guarantees": 4.5,
          "year": 2024
        }
      ],
      "keyStats": [
        {
          "label": "Pass Breakups (2023)",
          "value": "13",
          "rank": "Top 15 CB"
        },
        {
          "label": "Snaps Played",
          "value": "1,002",
          "rank": "Iron Man"
        },
        {
          "label": "Super Bowl Champion",
          "value": "SB LIII",
          "rank": "Proven Ring"
        }
      ]
    }
  },
  {
    "id": "samaje-perine",
    "name": "Samaje Perine",
    "position": "RB",
    "positionFull": "3rd-Down Pass Protection & Receiving Specialist",
    "age": 28,
    "team": "Denver Broncos",
    "teamLogoAbbr": "DEN",
    "rating": 84,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/liorwdmj8gelxh5u7rc4",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
    "teamColor": "#002244",
    "college": "Oklahoma",
    "dataSource": "spotrac",
    "tier": "JOURNEYMAN",
    "situationalTag": "53-MAN CUTDOWN BUBBLE (PASS-PRO SPECIALIST)",
    "contractType": "PROVE_IT",
    "healthDurability": 90,
    "schemeFitScore": 93,
    "schemeType": "Spread Option",
    "publicLeverageScore": 76,
    "patienceAndTrust": 72,
    "currentStatus": "Pending Extension",
    "currentSalary": 3.0,
    "warRoom": {
      "thesisStatement": "Perine is on the roster bubble in Denver due to youth movement. However, elite contenders like Kansas City desperately need a trusted veteran who catches passes and picks up blitzes on 3rd-and-long.",
      "leverageTimeline": [
        "CAMP SCRIMMAGE: Denver gives lion's share of carries to younger backs Javonte Williams and Jaleel McLaughlin.",
        "CUTDOWN APPROACH: Denver shops Perine for a late-round pick; releases him prior to Week 1.",
        "KC SIGNING: Chiefs immediately sign him to replace Clyde Edwards-Helaire on passing downs."
      ],
      "replacementCost": {
        "draftCapitalCost": "Costs zero draft picks if claimed or signed after cutdown.",
        "rookieVarianceDelta": "Rookie running backs blow blitz pickups 42% of the time, risking quarterback injury.",
        "capOpportunityCost": "Minimum cap investment ($1.5M - $3M) for Super Bowl tested 3rd-down competency.",
        "qbPressureDelta": "50 receptions on 56 targets (89.3% catch rate) with zero blitz errors in 2023.",
        "pickWasted": "Round 4, Pick 114"
      },
      "targetAsk": {
        "term": 1,
        "totalValue": 3.5,
        "aav": 3.5,
        "practicalGuarantees": 2.2,
        "firstYearCashFlowPct": 65
      },
      "comparables": [
        {
          "player": "Jerick McKinnon",
          "team": "KC",
          "aav": 1.3,
          "guarantees": 1.0,
          "year": 2023
        },
        {
          "player": "Latavius Murray",
          "team": "BUF",
          "aav": 1.3,
          "guarantees": 0.8,
          "year": 2023
        }
      ],
      "keyStats": [
        {
          "label": "Catch Rate",
          "value": "89.3%",
          "rank": "1st among RBs"
        },
        {
          "label": "Pass Pro Grade",
          "value": "83.1",
          "rank": "Top 3 NFL"
        },
        {
          "label": "Yards After Contact",
          "value": "3.2",
          "rank": "Power Back"
        }
      ]
    }
  },
  {
    "id": "malik-nabers",
    "name": "Malik Nabers",
    "position": "WR",
    "positionFull": "Dynamic WR1 / #6 Overall Pick",
    "age": 21,
    "team": "New York Giants",
    "teamLogoAbbr": "NYG",
    "rating": 92,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/w3edoyyuomqlovvp9ixc",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
    "teamColor": "#0B2265",
    "college": "LSU",
    "dataSource": "spotrac",
    "tier": "ROOKIE",
    "situationalTag": "ROOKIE SCALE DISPUTE (UPFRONT BONUS & ZERO-OFFSET)",
    "contractType": "ROOKIE_SCALE",
    "healthDurability": 94,
    "schemeFitScore": 98,
    "schemeType": "Spread Option",
    "publicLeverageScore": 94,
    "patienceAndTrust": 80,
    "currentStatus": "Pending Extension",
    "currentSalary": 7.3,
    "warRoom": {
      "thesisStatement": "While the 4-year, $29.2M total value is slotted by the CBA rookie wage scale, the strategic war room battle is over upfront signing bonus payment dates and the elimination of offset language.",
      "leverageTimeline": [
        "POST-DRAFT: Giants select Nabers #6 overall to be the franchise alpha receiver.",
        "CAMP DISPUTE: Giants seek to defer 50% of the $18.1M signing bonus into 2025; RAID demands 100% payout within 15 days.",
        "OFFSET BATTLE: Fighting to ensure zero offset language so Nabers retains full guarantees if ever traded or cut in Year 4."
      ],
      "replacementCost": {
        "draftCapitalCost": "Giants invested Pick 6; Daniel Jones' career survival hinges entirely on Nabers creating explosive separation.",
        "rookieVarianceDelta": "Giants passing offense ranked 31st in explosive plays in 2023; Nabers creates instant 15+ yard threat.",
        "capOpportunityCost": "100% slotted rookie cap hits ($5.3M in Year 1) provide massive surplus value compared to veteran WRs.",
        "qbPressureDelta": "Led all college receivers in 2023 with 34 explosive catches of 20+ yards.",
        "pickWasted": "Round 1, Pick 6"
      },
      "targetAsk": {
        "term": 4,
        "totalValue": 29.2,
        "aav": 7.3,
        "practicalGuarantees": 29.2,
        "firstYearCashFlowPct": 65
      },
      "comparables": [
        {
          "player": "Marvin Harrison Jr",
          "team": "ARI",
          "aav": 9.2,
          "guarantees": 36.8,
          "year": 2024
        },
        {
          "player": "Rome Odunze",
          "team": "CHI",
          "aav": 5.6,
          "guarantees": 22.7,
          "year": 2024
        }
      ],
      "keyStats": [
        {
          "label": "College Yds/Catch (2023)",
          "value": "17.6",
          "rank": "1st in FBS"
        },
        {
          "label": "Slotted Signing Bonus",
          "value": "$18.1M",
          "rank": "100% Guaranteed"
        },
        {
          "label": "Explosive Plays (20+ yds)",
          "value": "34",
          "rank": "Nation Leader"
        }
      ]
    }
  },
  {
    "id": "joe-alt",
    "name": "Joe Alt",
    "position": "OT",
    "positionFull": "Foundational Right Tackle / #5 Overall Pick",
    "age": 21,
    "team": "Los Angeles Chargers",
    "teamLogoAbbr": "LAC",
    "rating": 91,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/xn3px9imparnxiepwbox",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
    "teamColor": "#007BC7",
    "college": "Notre Dame",
    "dataSource": "spotrac",
    "tier": "ROOKIE",
    "situationalTag": "TOP-5 ROOKIE ANCHOR (RT TRANSITION)",
    "contractType": "ROOKIE_SCALE",
    "healthDurability": 96,
    "schemeFitScore": 99,
    "schemeType": "Power Gap",
    "publicLeverageScore": 92,
    "patienceAndTrust": 85,
    "currentStatus": "Pending Extension",
    "currentSalary": 8.3,
    "warRoom": {
      "thesisStatement": "Jim Harbaugh and Joe Hortiz drafted Joe Alt #5 overall to establish an impenetrable offensive line. Switching from Notre Dame LT to NFL RT, Alt's rookie contract structure establishes precedent for offensive tackle wage slotting.",
      "leverageTimeline": [
        "DRAFT DAY: Chargers pass on Malik Nabers to draft Alt, signaling a trench-first identity.",
        "CAMP TRANSITION: Alt takes 100% of first-team right tackle reps against Joey Bosa and Khalil Mack in camp.",
        "BONUS STRUCTURE: Negotiating immediate signing bonus distribution and roster workout escalator protections."
      ],
      "replacementCost": {
        "draftCapitalCost": "Chargers spent #5 overall; Justin Herbert's pass protection is non-negotiable.",
        "rookieVarianceDelta": "Chargers allowed 43 sacks in 2023; Alt pairing with Rashawn Slater forms an elite young tackle tandem.",
        "capOpportunityCost": "Slotted 4-year, $33.2M deal saves $15M/yr compared to veteran tackle market.",
        "qbPressureDelta": "Allowed only 1 sack on 712 pass-blocking snaps over his final two college seasons.",
        "pickWasted": "Round 1, Pick 5"
      },
      "targetAsk": {
        "term": 4,
        "totalValue": 33.2,
        "aav": 8.3,
        "practicalGuarantees": 33.2,
        "firstYearCashFlowPct": 65
      },
      "comparables": [
        {
          "player": "Penei Sewell (Rookie)",
          "team": "DET",
          "aav": 6.0,
          "guarantees": 24.1,
          "year": 2021
        },
        {
          "player": "Peter Skoronski",
          "team": "TEN",
          "aav": 4.9,
          "guarantees": 19.6,
          "year": 2023
        }
      ],
      "keyStats": [
        {
          "label": "Pass Block Win Rate (College)",
          "value": "99.1%",
          "rank": "1st in Nation"
        },
        {
          "label": "Height / Weight",
          "value": "6'9\" / 322 lbs",
          "rank": "Towering Frame"
        },
        {
          "label": "Sacks Allowed (2 Yrs)",
          "value": "1",
          "rank": "Elite Anchor"
        }
      ]
    }
  }
];

export const REAL_GM_PROFILES: Record<string, GMProfile> = {
  "ceedee-lamb": {
    "id": "gm-jerry-jones",
    "name": "Jerry Jones & Will McClay",
    "team": "Dallas Cowboys",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
    "teamColor": "#002244",
    "archetype": "Win-Now Aggressor",
    "philosophy": "Operates under vanity, public drama, and owner ego; insists on dragging talks until public pressure peaks, then caves with massive guarantees.",
    "draftPick": "Round 1, Pick 24",
    "teamCapSpace": 22.4,
    "patience": 65,
    "acceptanceScore": 45,
    "currentMood": "Skeptical",
    "currentStance": "I've said it before: I don't have a sense of urgency. We have CeeDee under contract for $17.9M. If he wants $34M like Justin Jefferson, he needs to come to camp and stop the fines."
  },
  "trent-williams": {
    "id": "gm-john-lynch",
    "name": "John Lynch & Kyle Shanahan",
    "team": "San Francisco 49ers",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
    "teamColor": "#AA0000",
    "archetype": "Win-Now Aggressor",
    "philosophy": "Urgent championship window after Super Bowl LVIII heartbreak; recognizes that Brock Purdy and Christian McCaffrey cannot function without Trent Williams.",
    "draftPick": "Round 1, Pick 31",
    "teamCapSpace": 48.0,
    "patience": 78,
    "acceptanceScore": 52,
    "currentMood": "Cornered",
    "currentStance": "We respect Trent more than any player in this locker room. But he has 3 years left on his deal. We are willing to convert his non-guaranteed base into upfront signing bonus cash, but we need cap room for Aiyuk."
  },
  "haason-reddick": {
    "id": "gm-joe-douglas",
    "name": "Joe Douglas",
    "team": "New York Jets",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
    "teamColor": "#003F2D",
    "archetype": "Analytics/Value GM",
    "philosophy": "Disciplined trenches evaluator who refuses to be extorted by trade acquisitions; holds firm on team leverage despite escalating media noise.",
    "draftPick": "Round 1, Pick 10",
    "teamCapSpace": 16.8,
    "patience": 55,
    "acceptanceScore": 38,
    "currentMood": "Defensive",
    "currentStance": "We traded for Haason with the understanding he would play on his existing contract. We will NOT negotiate an extension while he is incurring daily holdout fines. Report to camp, and we will talk."
  },
  "justin-simmons": {
    "id": "gm-terry-fontenot",
    "name": "Terry Fontenot",
    "team": "Atlanta Falcons",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
    "teamColor": "#A71930",
    "archetype": "Win-Now Aggressor",
    "philosophy": "All-in on winning the NFC South with veteran acquisitions (Kirk Cousins, Matthew Judon); views Simmons as the final championship defensive piece.",
    "draftPick": "Round 1, Pick 8",
    "teamCapSpace": 12.2,
    "patience": 85,
    "acceptanceScore": 55,
    "currentMood": "Intrigued",
    "currentStance": "We have Jessie Bates holding down free safety. If you agree to a 1-year deal at $7.5M with $4.5M guaranteed, we can insert $2M in playoff/Pro Bowl escalators and finalize before Week 1."
  },
  "stephon-gilmore": {
    "id": "gm-kwesi-adofo-mensah",
    "name": "Kwesi Adofo-Mensah",
    "team": "Minnesota Vikings",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
    "teamColor": "#4F2683",
    "archetype": "Analytics/Value GM",
    "philosophy": "Wall Street analytics background; normally resists paying aging veterans, but injury emergency in secondary forces a calculated short-term overpay.",
    "draftPick": "Round 1, Pick 10",
    "teamCapSpace": 19.5,
    "patience": 80,
    "acceptanceScore": 60,
    "currentMood": "Pressured",
    "currentStance": "Brian Flores wants Gilmore in press-man on Day 1. We can do 1 year, $10M with $7M fully guaranteed. That protects your client and solves our catastrophic camp injuries."
  },
  "samaje-perine": {
    "id": "gm-brett-veach",
    "name": "Brett Veach",
    "team": "Kansas City Chiefs",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
    "teamColor": "#E31837",
    "archetype": "Win-Now Aggressor",
    "philosophy": "Master of veteran 3rd-down role players; prioritizes blitz pickup security for Patrick Mahomes over raw athletic upside.",
    "draftPick": "Round 1, Pick 32",
    "teamCapSpace": 15.0,
    "patience": 80,
    "acceptanceScore": 50,
    "currentMood": "Intrigued",
    "currentStance": "We need a veteran who doesn't miss blitz assignments on 3rd down. If Denver waives him, we'll sign him to a 1-year, $1.5M deal with per-game active roster bonuses."
  },
  "malik-nabers": {
    "id": "gm-joe-schoen",
    "name": "Joe Schoen",
    "team": "New York Giants",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
    "teamColor": "#0B2265",
    "archetype": "Cap Conservative",
    "philosophy": "Disciplined cap architect; respects rookie wage scale boundaries and refuses to set dangerous organizational precedent on offset language.",
    "draftPick": "Round 1, Pick 6",
    "teamCapSpace": 18.0,
    "patience": 75,
    "acceptanceScore": 48,
    "currentMood": "Intrigued",
    "currentStance": "The 4-year, $29.2M deal is fixed by the CBA slotting. We are willing to accelerate 70% of the signing bonus into 2024, but standard club offset language must remain."
  },
  "joe-alt": {
    "id": "gm-joe-hortiz",
    "name": "Joe Hortiz & Jim Harbaugh",
    "team": "Los Angeles Chargers",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
    "teamColor": "#007BC7",
    "archetype": "Analytics/Value GM",
    "philosophy": "Baltimore Ravens pedigree; built from the inside out. Believes offensive line is the bedrock of championship football.",
    "draftPick": "Round 1, Pick 5",
    "teamCapSpace": 22.0,
    "patience": 85,
    "acceptanceScore": 55,
    "currentMood": "Ready to Sign",
    "currentStance": "Joe Alt is our cornerstone right tackle. We're ready to sign the standard 4-year slotted deal ($33.2M fully guaranteed) with upfront bonus payout. Let's get him on the field."
  }
};

export const REAL_SCOUTING_PROSPECTS: Client[] = [
  {
    "id": "justin-simmons",
    "name": "Justin Simmons",
    "position": "S",
    "positionFull": "Two-Time All-Pro Free Safety / Secondary Leader",
    "age": 30,
    "team": "Atlanta Falcons",
    "teamLogoAbbr": "ATL",
    "rating": 90,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/hepfele9gi8zbjin8kbf",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
    "teamColor": "#A71930",
    "college": "Boston College",
    "dataSource": "spotrac",
    "tier": "JOURNEYMAN",
    "situationalTag": "CAP CASUALTY PROVE-IT DEAL (LATE AUGUST SIGNING)",
    "contractType": "PROVE_IT",
    "healthDurability": 90,
    "schemeFitScore": 97,
    "schemeType": "Split-Safety",
    "publicLeverageScore": 84,
    "patienceAndTrust": 80,
    "currentStatus": "Pending Extension",
    "currentSalary": 7.5,
    "warRoom": {
      "thesisStatement": "Released by Denver in March as a $14.5M cap casualty despite earning 2nd-Team All-Pro honors. He patient waited out the market until training camp injuries created an urgent vacancy in Atlanta's secondary.",
      "leverageTimeline": [
        "MARCH: Released by Broncos; refuses lowball early free agency safety offers.",
        "AUGUST 12: Visits New Orleans and Atlanta; Falcons aggressively move to seal the deal to pair with Jessie Bates III.",
        "CONTRACT GOAL: Secure a 1-year prove-it structure with $5M+ guaranteed and achievable interception escalators."
      ],
      "replacementCost": {
        "draftCapitalCost": "Falcons spent draft capital on Michael Penix Jr; secondary needed instant veteran communication.",
        "rookieVarianceDelta": "Pairing Simmons with Jessie Bates III gives Atlanta the #1 safety tandem in EPA allowed.",
        "capOpportunityCost": "Signing Simmons at $7.5M is a discount compared to multi-year safety commitments.",
        "qbPressureDelta": "30 career interceptions (leads all NFL defenders since 2016).",
        "pickWasted": "Round 3, Pick 98"
      },
      "targetAsk": {
        "term": 1,
        "totalValue": 8.0,
        "aav": 8.0,
        "practicalGuarantees": 6.0,
        "firstYearCashFlowPct": 60
      },
      "comparables": [
        {
          "player": "Jordan Poyer",
          "team": "MIA",
          "aav": 2.0,
          "guarantees": 1.0,
          "year": 2024
        },
        {
          "player": "Geno Stone",
          "team": "CIN",
          "aav": 7.0,
          "guarantees": 6.0,
          "year": 2024
        }
      ],
      "keyStats": [
        {
          "label": "Career Interceptions",
          "value": "30",
          "rank": "1st in NFL"
        },
        {
          "label": "All-Pro Honors",
          "value": "4x",
          "rank": "Elite Pedigree"
        },
        {
          "label": "Passer Rating in Coverage",
          "value": "59.4",
          "rank": "Top 5 Safety"
        }
      ]
    }
  },
  {
    "id": "stephon-gilmore",
    "name": "Stephon Gilmore",
    "position": "EDGE",
    "positionFull": "Former Defensive Player of the Year / Boundary CB",
    "age": 33,
    "team": "Minnesota Vikings",
    "teamLogoAbbr": "MIN",
    "rating": 88,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/rzqv9harev8c0excxzfz",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
    "teamColor": "#4F2683",
    "college": "South Carolina",
    "dataSource": "spotrac",
    "tier": "JOURNEYMAN",
    "situationalTag": "EMERGENCY CAMP SIGNING (SECONDARY INJURY REPLACEMENT)",
    "contractType": "PROVE_IT",
    "healthDurability": 86,
    "schemeFitScore": 96,
    "schemeType": "Man Coverage",
    "publicLeverageScore": 86,
    "patienceAndTrust": 82,
    "currentStatus": "Pending Extension",
    "currentSalary": 10.0,
    "warRoom": {
      "thesisStatement": "Minnesota suffered devastating training camp injuries in their secondary (Mekhi Blackmon torn ACL, Shaquill Griffin hamstring). Brian Flores' blitz-heavy scheme requires an experienced boundary corner who can hold up on an island.",
      "leverageTimeline": [
        "AUGUST 2: Vikings lose starting CB Blackmon to season-ending ACL injury in first scrimmage.",
        "AUGUST 11: Kwesi Adofo-Mensah flies Gilmore in for emergency physical and meeting with Brian Flores.",
        "AUGUST 18: Gilmore agrees to terms on a 1-year contract worth up to $10M ($7M fully guaranteed)."
      ],
      "replacementCost": {
        "draftCapitalCost": "Zero draft options in August; waiver wire corners lack press-man capability.",
        "rookieVarianceDelta": "Flores blitzes on 51% of snaps; playing backup corners in Cover 0 results in explosive touchdowns.",
        "capOpportunityCost": "Minnesota has surplus cap space; paying for Gilmore prevents defensive collapse.",
        "qbPressureDelta": "Allowed just 54.4% completion rate on 580 coverage snaps in Dallas in 2023.",
        "pickWasted": "Round 1, Pick 10"
      },
      "targetAsk": {
        "term": 1,
        "totalValue": 10.0,
        "aav": 10.0,
        "practicalGuarantees": 7.0,
        "firstYearCashFlowPct": 70
      },
      "comparables": [
        {
          "player": "Patrick Peterson",
          "team": "PIT",
          "aav": 7.0,
          "guarantees": 5.8,
          "year": 2023
        },
        {
          "player": "Adoree' Jackson",
          "team": "NYG",
          "aav": 6.0,
          "guarantees": 4.5,
          "year": 2024
        }
      ],
      "keyStats": [
        {
          "label": "Pass Breakups (2023)",
          "value": "13",
          "rank": "Top 15 CB"
        },
        {
          "label": "Snaps Played",
          "value": "1,002",
          "rank": "Iron Man"
        },
        {
          "label": "Super Bowl Champion",
          "value": "SB LIII",
          "rank": "Proven Ring"
        }
      ]
    }
  },
  {
    "id": "samaje-perine",
    "name": "Samaje Perine",
    "position": "RB",
    "positionFull": "3rd-Down Pass Protection & Receiving Specialist",
    "age": 28,
    "team": "Denver Broncos",
    "teamLogoAbbr": "DEN",
    "rating": 84,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/liorwdmj8gelxh5u7rc4",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
    "teamColor": "#002244",
    "college": "Oklahoma",
    "dataSource": "spotrac",
    "tier": "JOURNEYMAN",
    "situationalTag": "53-MAN CUTDOWN BUBBLE (PASS-PRO SPECIALIST)",
    "contractType": "PROVE_IT",
    "healthDurability": 90,
    "schemeFitScore": 93,
    "schemeType": "Spread Option",
    "publicLeverageScore": 76,
    "patienceAndTrust": 72,
    "currentStatus": "Pending Extension",
    "currentSalary": 3.0,
    "warRoom": {
      "thesisStatement": "Perine is on the roster bubble in Denver due to youth movement. However, elite contenders like Kansas City desperately need a trusted veteran who catches passes and picks up blitzes on 3rd-and-long.",
      "leverageTimeline": [
        "CAMP SCRIMMAGE: Denver gives lion's share of carries to younger backs Javonte Williams and Jaleel McLaughlin.",
        "CUTDOWN APPROACH: Denver shops Perine for a late-round pick; releases him prior to Week 1.",
        "KC SIGNING: Chiefs immediately sign him to replace Clyde Edwards-Helaire on passing downs."
      ],
      "replacementCost": {
        "draftCapitalCost": "Costs zero draft picks if claimed or signed after cutdown.",
        "rookieVarianceDelta": "Rookie running backs blow blitz pickups 42% of the time, risking quarterback injury.",
        "capOpportunityCost": "Minimum cap investment ($1.5M - $3M) for Super Bowl tested 3rd-down competency.",
        "qbPressureDelta": "50 receptions on 56 targets (89.3% catch rate) with zero blitz errors in 2023.",
        "pickWasted": "Round 4, Pick 114"
      },
      "targetAsk": {
        "term": 1,
        "totalValue": 3.5,
        "aav": 3.5,
        "practicalGuarantees": 2.2,
        "firstYearCashFlowPct": 65
      },
      "comparables": [
        {
          "player": "Jerick McKinnon",
          "team": "KC",
          "aav": 1.3,
          "guarantees": 1.0,
          "year": 2023
        },
        {
          "player": "Latavius Murray",
          "team": "BUF",
          "aav": 1.3,
          "guarantees": 0.8,
          "year": 2023
        }
      ],
      "keyStats": [
        {
          "label": "Catch Rate",
          "value": "89.3%",
          "rank": "1st among RBs"
        },
        {
          "label": "Pass Pro Grade",
          "value": "83.1",
          "rank": "Top 3 NFL"
        },
        {
          "label": "Yards After Contact",
          "value": "3.2",
          "rank": "Power Back"
        }
      ]
    }
  },
  {
    "id": "malik-nabers",
    "name": "Malik Nabers",
    "position": "WR",
    "positionFull": "Dynamic WR1 / #6 Overall Pick",
    "age": 21,
    "team": "New York Giants",
    "teamLogoAbbr": "NYG",
    "rating": 92,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/w3edoyyuomqlovvp9ixc",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
    "teamColor": "#0B2265",
    "college": "LSU",
    "dataSource": "spotrac",
    "tier": "ROOKIE",
    "situationalTag": "ROOKIE SCALE DISPUTE (UPFRONT BONUS & ZERO-OFFSET)",
    "contractType": "ROOKIE_SCALE",
    "healthDurability": 94,
    "schemeFitScore": 98,
    "schemeType": "Spread Option",
    "publicLeverageScore": 94,
    "patienceAndTrust": 80,
    "currentStatus": "Pending Extension",
    "currentSalary": 7.3,
    "warRoom": {
      "thesisStatement": "While the 4-year, $29.2M total value is slotted by the CBA rookie wage scale, the strategic war room battle is over upfront signing bonus payment dates and the elimination of offset language.",
      "leverageTimeline": [
        "POST-DRAFT: Giants select Nabers #6 overall to be the franchise alpha receiver.",
        "CAMP DISPUTE: Giants seek to defer 50% of the $18.1M signing bonus into 2025; RAID demands 100% payout within 15 days.",
        "OFFSET BATTLE: Fighting to ensure zero offset language so Nabers retains full guarantees if ever traded or cut in Year 4."
      ],
      "replacementCost": {
        "draftCapitalCost": "Giants invested Pick 6; Daniel Jones' career survival hinges entirely on Nabers creating explosive separation.",
        "rookieVarianceDelta": "Giants passing offense ranked 31st in explosive plays in 2023; Nabers creates instant 15+ yard threat.",
        "capOpportunityCost": "100% slotted rookie cap hits ($5.3M in Year 1) provide massive surplus value compared to veteran WRs.",
        "qbPressureDelta": "Led all college receivers in 2023 with 34 explosive catches of 20+ yards.",
        "pickWasted": "Round 1, Pick 6"
      },
      "targetAsk": {
        "term": 4,
        "totalValue": 29.2,
        "aav": 7.3,
        "practicalGuarantees": 29.2,
        "firstYearCashFlowPct": 65
      },
      "comparables": [
        {
          "player": "Marvin Harrison Jr",
          "team": "ARI",
          "aav": 9.2,
          "guarantees": 36.8,
          "year": 2024
        },
        {
          "player": "Rome Odunze",
          "team": "CHI",
          "aav": 5.6,
          "guarantees": 22.7,
          "year": 2024
        }
      ],
      "keyStats": [
        {
          "label": "College Yds/Catch (2023)",
          "value": "17.6",
          "rank": "1st in FBS"
        },
        {
          "label": "Slotted Signing Bonus",
          "value": "$18.1M",
          "rank": "100% Guaranteed"
        },
        {
          "label": "Explosive Plays (20+ yds)",
          "value": "34",
          "rank": "Nation Leader"
        }
      ]
    }
  },
  {
    "id": "joe-alt",
    "name": "Joe Alt",
    "position": "OT",
    "positionFull": "Foundational Right Tackle / #5 Overall Pick",
    "age": 21,
    "team": "Los Angeles Chargers",
    "teamLogoAbbr": "LAC",
    "rating": 91,
    "headshotUrl": "https://static.www.nfl.com/image/upload/f_auto,q_auto/league/xn3px9imparnxiepwbox",
    "teamLogoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
    "teamColor": "#007BC7",
    "college": "Notre Dame",
    "dataSource": "spotrac",
    "tier": "ROOKIE",
    "situationalTag": "TOP-5 ROOKIE ANCHOR (RT TRANSITION)",
    "contractType": "ROOKIE_SCALE",
    "healthDurability": 96,
    "schemeFitScore": 99,
    "schemeType": "Power Gap",
    "publicLeverageScore": 92,
    "patienceAndTrust": 85,
    "currentStatus": "Pending Extension",
    "currentSalary": 8.3,
    "warRoom": {
      "thesisStatement": "Jim Harbaugh and Joe Hortiz drafted Joe Alt #5 overall to establish an impenetrable offensive line. Switching from Notre Dame LT to NFL RT, Alt's rookie contract structure establishes precedent for offensive tackle wage slotting.",
      "leverageTimeline": [
        "DRAFT DAY: Chargers pass on Malik Nabers to draft Alt, signaling a trench-first identity.",
        "CAMP TRANSITION: Alt takes 100% of first-team right tackle reps against Joey Bosa and Khalil Mack in camp.",
        "BONUS STRUCTURE: Negotiating immediate signing bonus distribution and roster workout escalator protections."
      ],
      "replacementCost": {
        "draftCapitalCost": "Chargers spent #5 overall; Justin Herbert's pass protection is non-negotiable.",
        "rookieVarianceDelta": "Chargers allowed 43 sacks in 2023; Alt pairing with Rashawn Slater forms an elite young tackle tandem.",
        "capOpportunityCost": "Slotted 4-year, $33.2M deal saves $15M/yr compared to veteran tackle market.",
        "qbPressureDelta": "Allowed only 1 sack on 712 pass-blocking snaps over his final two college seasons.",
        "pickWasted": "Round 1, Pick 5"
      },
      "targetAsk": {
        "term": 4,
        "totalValue": 33.2,
        "aav": 8.3,
        "practicalGuarantees": 33.2,
        "firstYearCashFlowPct": 65
      },
      "comparables": [
        {
          "player": "Penei Sewell (Rookie)",
          "team": "DET",
          "aav": 6.0,
          "guarantees": 24.1,
          "year": 2021
        },
        {
          "player": "Peter Skoronski",
          "team": "TEN",
          "aav": 4.9,
          "guarantees": 19.6,
          "year": 2023
        }
      ],
      "keyStats": [
        {
          "label": "Pass Block Win Rate (College)",
          "value": "99.1%",
          "rank": "1st in Nation"
        },
        {
          "label": "Height / Weight",
          "value": "6'9\" / 322 lbs",
          "rank": "Towering Frame"
        },
        {
          "label": "Sacks Allowed (2 Yrs)",
          "value": "1",
          "rank": "Elite Anchor"
        }
      ]
    }
  }
];

export const NFL_DATA_SOURCE_META = {
  sourceNflverse: "https://github.com/nflverse/nflverse-data",
  sourceSpotrac: "https://www.spotrac.com/nfl/free-agents/",
  totalRosteredPlayers: 3061,
  totalTeams: 36,
  lastSyncTimestamp: "2026-09-24T15:55:46.103808",
  status: "PRESEASON_2024_ACTIVE"
};
